//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poker.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDB
    {
        public RoomDB()
        {
            this.Leagues = new HashSet<LeagueDB>();
        }
    
        public int id { get; set; }
        public string gamePolicy { get; set; }
        public int maxPlayers { get; set; }
        public int minPlayers { get; set; }
        public int minBuyIn { get; set; }
        public int maxBuyIn { get; set; }
        public bool allowSpectating { get; set; }
        public int bigBlind { get; set; }
    
        public virtual ICollection<LeagueDB> Leagues { get; set; }
    }
}
